# Project information
site_name: muh Test wiki thing
site_description: Insert description
site_author: memememe
site_url: https://testwiki.netlify.com/

# Change this to your discord invite link
repo_name: Join my community Discord
repo_url: https://discord.gg/invitelink
edit_uri: ""

#Change the link too
extra:
  social:
    - type: discord
      link: https://discord.gg/invitelink

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'Blue Grey'
    accent: 'Cyan'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  
#extensions
markdown_extensions:
  - admonition

# You can set custom order for the nav items (side menu)
# If you don't put anything, the menu will be built automatically
# You can edit this too, but I'm leaving it off so you can decide
# wether edit manually or let mkdocs decide how to do it.

# Here's an example of a nav structure

nav:
   - Home: 'index.md'
   - System:
     - System: '1-System/basics.md'
   - Character Overview:
     - Sol Badguy: '2-Overview/sol.md'
   - Gameplan:
     - Johnny: '3-Gameplan/johnny.md'
   - Combos:
     - Kum Haehyun: '4-Combos/kum.md'
   - Frame Data:
     - Ky Kiske: '5-Framedata/ky.md'
   - Match Up:
     - Against Dizzy: '6-Matchup/against-dizzy.md'
