# Project information
site_name: muh Test wiki thing
site_description: Insert description
site_author: memememe
site_url: https://testwiki.netlify.com/

# Change this to your discord invite link
repo_name: Join my community Discord
repo_url: https://discord.gg/invitelink
edit_uri: ""

#Change the link too
extra:
  social:
    - type: discord
      link: https://discord.gg/invitelink

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'Green Grey'
    accent: 'Cyan'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  
#extensions
markdown_extensions:
  - admonition

# You can set custom order for the nav items (side menu)
# If you don't put anything, the menu will be built automatically
# You can edit this too, but I'm leaving it off so you can decide
# wether edit manually or let mkdocs decide how to do it.

# Here's an example of a nav structure

nav:
   - Home: 'index.md'
   - System:
     - Basics: '1-System/basics.md'
     - Notions of Neutral Game: '1-System/notions-about-neutral-game.md'
     - Offense in GGRev2: '1-System/offense-in-ggxrd-rev2.md'
     - Defense in GGRev2: '1-System/defense-in-ggxrd-rev2.md'
     - Glossary:
        - Glossary: '1-System/glossary.md'
   - Character Overview:
     - I-No: '2-Overview/i-no.md'
     - Ky Kiske: '2-Overview/ky.md'
     - Sol Badguy: '2-Overview/sol.md'
   - Gameplan:
     - Axl Low: '3-Gameplan/axl.md'
     - Faust: '3-Gameplan/faust.md'
     - Johnny: '3-Gameplan/johnny.md'
   - Combos:
     - Kum Haehyun: '4-Combos/kum.md'
     - May: '4-Combos/may.md'
     - Potemkin: '4-Combos/potemkin.md'
   - Frame Data:
     - Ky Kiske: '5-Framedata/ky.md'
     - Leo Whitefang: '5-Framedata/leo.md'
     - Slayer: '5-Framedata/slayer.md'
   - Match Up:
     - Against Dizzy: '6-Matchup/against-dizzy.md'
     - Against Elphelt Valentine: '6-Matchup/against-elphelt.md'
     - Against Johnny: '6-Matchup/against-johnny.md'
