backend:
  name: git-gateway
  # Edit the repo
  # example: repo: fabricioanciaes/fexlguide
  # the repo name is what you've inserted when you clicked the netlify deploy button
  repo: gureniro/test
  branch: master

public_folder: "/images/"
media_folder: "/docs/images"
publish_mode: editorial_workflow


# Collections are categories in the side menu.
# It comes built in with General, Characters and System.
# The general ones are in the root, that means they arent in a submenu
# To create a new category you can just copy one of them and commit.
# Make sure identation is correct (YES, the number of spaces matter)

collections:
  - name: "General"
    label: "General"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Summary", name: "summary", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}

  - name: "Game Systems"
    label: "Game Systems"
    folder: "docs/system"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Char Overview"
    label: "Char Overview"
    folder: "docs/overview"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Game Plans"
    label: "Game Plans"
    folder: "docs/gameplan"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Combos"
    label: "Combos"
    folder: "docs/combos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "Frame Data"
    label: "Frame Data"
    folder: "docs/framedata"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
